Misc Yocto Wrynose (gcc 16.1) fixes (#2727)
For replication, setup info: 

- GCC: 16.1 
- glibc: 2.43
- target architecture build: aarch64
- Config used to setup Yocto layers:
[Config](https://git.ti.com/cgit/arago-project/oe-layersetup/tree/configs/arago-master-config.txt)


While building Yocto wrynose, recipe in meta-oe layer, following errors
appeared:

1\)
```
test_conformance/commonfns/test_unary_fn.cpp:113:21: error: variable 'j' set but not used [-Werror=unused-but-set-variable=]
  113 |     for (int i = 0, j = 0; i < n; i++, j++)
      |                     ^
cc1plus: all warnings being treated as errors
```
2)
```
test_conformance/extensions/cl_khr_command_buffer/command_buffer_printf.cpp:286:25: error: array subscript -1 is outside array bounds of 'signed char []' [-Werror=array-bounds=]
  286 |             pattern.back() = '\0';
      |             ~~~~~~~~~~~~^~
cc1plus: all warnings being treated as errors
```

Patches [test_unary_fn: Remove unused variable
j](https://github.com/KhronosGroup/OpenCL-CTS/commit/51cab19be5be5f011705e75dcef3c360163f41a1)
and [command_buffer_printf: Fix out of bounds pattern
array](https://github.com/KhronosGroup/OpenCL-CTS/commit/1080490bd80b1f7ee0e58e275eddb2782edd939f)
solve the above.

I am also including [c11_atomics: Remove -Wno-format
flag](https://github.com/KhronosGroup/OpenCL-CTS/commit/d2607370dec47198a93fe9abd1f65f269250f929)
as there are no format errors that come from c11_atomics dir.

---------

Signed-off-by: Antonios Christidis <a-christidis@ti.com>

Merged as agreed on 30Jun26 call