Format fixes commonfns (#2728)
For replication, setup info:
GCC: 16.1
glibc: 2.43
target architecture build: aarch64
Config used to setup Yocto layers:
[Config](https://git.ti.com/cgit/arago-project/oe-layersetup/tree/configs/arago-master-config.txt)

While building Yocto wrynose, recipe in meta-oe layer, following error
appears multiple times:

```
test_conformance/commonfns/test_binary_fn.cpp:274:40:   required from here
  274 |         error = test_binary_fn<cl_half>(device, context, queue, num_elems,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  275 |                                         fnName.c_str(), vecParam,
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
  276 |                                         max_verify<cl_half>);
      |                                         ~~~~~~~~~~~~~~~~~~~~

test_conformance/commonfns/test_binary_fn.cpp:219:72: error: format '%g' expects argument of type 'double', but argument 8 has type 'int' [-Werror=format=]
  219 |                     log_error("x[%d]=%g y[%d]=%g out[%d]=%g, expected %g. "
      |                                                                       ~^
      |                                                                        |
      |                                                                        double
      |                                                                       %d
......
  223 |                               conv_to_flt(out[k]), v, k, i, j, vecSize);
      |                                                    ~
      |                                                    |
      |                                                    int


```
The [commonfns: fix type mismatches across function
templates](https://github.com/KhronosGroup/OpenCL-CTS/commit/d85a92794aca418359d60cedc56ad1288e4dbd12)
patch fixes the above. This is also the only format error when building,
so
[commonfns: Remove -Wno-format
flag](https://github.com/KhronosGroup/OpenCL-CTS/commit/5b099b9c63ebf7b0ded4bc2470326de22c7296a4)
re-enables -W-format

---------

Signed-off-by: Antonios Christidis <a-christidis@ti.com>